print("Calculator Program")
print("--------------------")
x = float(input("Number 1: "))
y = float(input("Number 2: "))
print("--------------------")
print("Result of Number 1+2 is:",x+y)
print("Result of Number 1-2 is:",x-y)
print("Result of Number 1*2 is:",x*y)
print("Result of Number 1/2 is:",x/y)