print("Velocity Calculate Program")
print("--------------------")
s = float(input("Input Distance (km): "))
t = float(input("Input Time (hr): "))
v = s/t*5/18 # Velocity in (m/s)
print("--------------------")
print("Velocity is",s/t,"(km/hr) or",v,"(m/s)")